spring.application.name: exchange-service
server:
  port: 8000

exchange:
  disclaimer: disclaimer
  delay: 12

spring:
  config:
    import: optional:configserver:http://localhost:8888
    # Since it is a client, it should fetch its config from the config-server
    # For now we use the local one to be safe if server not yet started
